// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi_O8D20CypEeLFWpWHUs0yYYnQwwWp68',
    appId: '1:16727420321:web:29ec7fac03c03939202fe0',
    messagingSenderId: '16727420321',
    projectId: 'liveordertracking-4859a',
    authDomain: 'liveordertracking-4859a.firebaseapp.com',
    storageBucket: 'liveordertracking-4859a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJcYgL219RIcUaoSjhJQzo1X7F1VPVWEA',
    appId: '1:16727420321:android:817653817654b49e202fe0',
    messagingSenderId: '16727420321',
    projectId: 'liveordertracking-4859a',
    storageBucket: 'liveordertracking-4859a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDulCM5czKPDMw2RGix5eJlREbhsRGldd8',
    appId: '1:16727420321:ios:543b9aba0b9817ac202fe0',
    messagingSenderId: '16727420321',
    projectId: 'liveordertracking-4859a',
    storageBucket: 'liveordertracking-4859a.firebasestorage.app',
    iosBundleId: 'com.example.liveOrderTracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDulCM5czKPDMw2RGix5eJlREbhsRGldd8',
    appId: '1:16727420321:ios:543b9aba0b9817ac202fe0',
    messagingSenderId: '16727420321',
    projectId: 'liveordertracking-4859a',
    storageBucket: 'liveordertracking-4859a.firebasestorage.app',
    iosBundleId: 'com.example.liveOrderTracking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi_O8D20CypEeLFWpWHUs0yYYnQwwWp68',
    appId: '1:16727420321:web:3cdea5e874e53380202fe0',
    messagingSenderId: '16727420321',
    projectId: 'liveordertracking-4859a',
    authDomain: 'liveordertracking-4859a.firebaseapp.com',
    storageBucket: 'liveordertracking-4859a.firebasestorage.app',
  );

}